### ISSUE TITLE
pip installation fails

### ISSUE THREAD

**Issue by jmschrei** [uwescience/myria-python#37]
I tried running `pip install myria-python` as suggested on an Ubuntu machine with the Anaconda python distribution.

I get the following error: `IOError: [Errno 2] No such file or directory: 'README.md'`

The README.md file is in your github repo but is not present in the zip file put on pip. Either the setup.py file should not read the README.md file (a fork which I could handle) or the README.md file should be put in the dist zip file.

**Comment by dhalperi** [comment]
Thanks for reporting, @jmschrei ! Fixed in version 1.2.2 as part of PR #38
