### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by sophieclayton** [uwescience/myria-python#39]
this is probably an issue on my side as i am trying to upload a 17GB .csv file, but could someone take a look and shed some light on this error message:

```
D-128-208-239-205:aux_data sclayton$ myria_upload --user armbrustlab --program seaflow --relation gebco_bathy gebco_bathymetry.csv 
INFO:root:RelationKey = armbrustlab:seaflow:gebco_bathy
INFO:root:Schema = [('LONG_TYPE', ''), ('DOUBLE_TYPE', 'lon'), ('DOUBLE_TYPE', 'lat'), ('DOUBLE_TYPE', 'z')]
INFO:root:Myria schema: {"columnNames": ["", "lon", "lat", "z"], "columnTypes": ["LONG_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE"]}
INFO:root:Creating a binary file with struct.fmt=<qddd
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): rest.myria.cs.washington.edu
Traceback (most recent call last):
  File "/Users/sclayton/anaconda/bin/myria_upload", line 9, in <module>
    load_entry_point('myria-python==1.1.3', 'console_scripts', 'myria_upload')()
  File "/Users/sclayton/anaconda/lib/python2.7/site-packages/myria_python-1.1.3-py2.7.egg/myria/cmd/upload_file.py", line 250, in main
    args.overwrite, **kwargs)
  File "/Users/sclayton/anaconda/lib/python2.7/site-packages/myria_python-1.1.3-py2.7.egg/myria/connection.py", line 401, in upload_file
    % (r.status_code, r.text))
myria.errors.MyriaError: Error 400: 
```
thanks!

**Comment by dhalperi** [comment]
I'm sure this is fine, but can you double-check that you are using the
latest version of myria-python?

(git pull or pip install --upgrade)


----
Daniel Halperin
Director of Research for Scalable Data Analytics
eScience Institute
University of Washington

**Comment by sophieclayton** [comment]
updated myria-python, now it is broken... will get back to you once i have
it all fixed and can try uploading again.

On Tue, Feb 10, 2015 at 2:06 PM, Daniel Halperin <notifications@github.com>
wrote:

> I'm sure this is fine, but can you double-check that you are using the
> latest version of myria-python?
>
> (git pull or pip install --upgrade)
>
>
> ----
> Daniel Halperin
> Director of Research for Scalable Data Analytics
> eScience Institute
> University of Washington
>
> On Tue, Feb 10, 2015 at 1:54 PM, Sophie Clayton <notifications@github.com>
> wrote:
>
> > this is probably an issue on my side as i am trying to upload a 17GB .csv
> > file, but could someone take a look and shed some light on this error
> > message:
> >
> > D-128-208-239-205:aux_data sclayton$ myria_upload --user armbrustlab
> --program seaflow --relation gebco_bathy gebco_bathymetry.csv
> > INFO:root:RelationKey = armbrustlab:seaflow:gebco_bathy
> > INFO:root:Schema = [('LONG_TYPE', ''), ('DOUBLE_TYPE', 'lon'),
> ('DOUBLE_TYPE', 'lat'), ('DOUBLE_TYPE', 'z')]
> > INFO:root:Myria schema: {"columnNames": ["", "lon", "lat", "z"],
> "columnTypes": ["LONG_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE"]}
> > INFO:root:Creating a binary file with struct.fmt=<qddd
> > INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS
> connection (1): rest.myria.cs.washington.edu
> > Traceback (most recent call last):
> > File "/Users/sclayton/anaconda/bin/myria_upload", line 9, in <module>
> > load_entry_point('myria-python==1.1.3', 'console_scripts',
> 'myria_upload')()
> > File
> "/Users/sclayton/anaconda/lib/python2.7/site-packages/myria_python-1.1.3-py2.7.egg/myria/cmd/upload_file.py",
> line 250, in main
> > args.overwrite, **kwargs)
> > File
> "/Users/sclayton/anaconda/lib/python2.7/site-packages/myria_python-1.1.3-py2.7.egg/myria/connection.py",
> line 401, in upload_file
> > % (r.status_code, r.text))
> > myria.errors.MyriaError: Error 400:
> >
> > thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/uwescience/myria-python/issues/39>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwescience/myria-python/issues/39#issuecomment-73794270>
> .
>



-- 
Sophie Clayton, PhD
School of Oceanography
Box 357940
University of Washington
Seattle, WA 98195, USA

tel: +1 (206) 685-1047
http://sophieclayton.github.io
http://armbrustlab.ocean.washington.edu/people/clayton

**Comment by billhowe** [comment]
Looking ahead: Do we have an example of a physical plan that can access
data from S3?  I think our theory is that will Just Work thanks to HDFS.

If so, that's another way to get semi-large datasets into Myria: Get them
into S3 first, then query them in parallel.

Of course, this won't be exposed in MyriaL.

On Tue, Feb 10, 2015 at 1:54 PM, Sophie Clayton <notifications@github.com>
wrote:

> this is probably an issue on my side as i am trying to upload a 17GB .csv
> file, but could someone take a look and shed some light on this error
> message:
>
> D-128-208-239-205:aux_data sclayton$ myria_upload --user armbrustlab --program seaflow --relation gebco_bathy gebco_bathymetry.csv
> INFO:root:RelationKey = armbrustlab:seaflow:gebco_bathy
> INFO:root:Schema = [('LONG_TYPE', ''), ('DOUBLE_TYPE', 'lon'), ('DOUBLE_TYPE', 'lat'), ('DOUBLE_TYPE', 'z')]
> INFO:root:Myria schema: {"columnNames": ["", "lon", "lat", "z"], "columnTypes": ["LONG_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE"]}
> INFO:root:Creating a binary file with struct.fmt=<qddd
> INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): rest.myria.cs.washington.edu
> Traceback (most recent call last):
>   File "/Users/sclayton/anaconda/bin/myria_upload", line 9, in <module>
>     load_entry_point('myria-python==1.1.3', 'console_scripts', 'myria_upload')()
>   File "/Users/sclayton/anaconda/lib/python2.7/site-packages/myria_python-1.1.3-py2.7.egg/myria/cmd/upload_file.py", line 250, in main
>     args.overwrite, **kwargs)
>   File "/Users/sclayton/anaconda/lib/python2.7/site-packages/myria_python-1.1.3-py2.7.egg/myria/connection.py", line 401, in upload_file
>     % (r.status_code, r.text))
> myria.errors.MyriaError: Error 400:
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwescience/myria-python/issues/39>.
>



-- 
Bill Howe
Associate Director and Senior Data Science Fellow, UW eScience Institute
Affiliate Faculty, Computer Science & Engineering
University of Washington
To acknowledge eScience: "Supported in part by the University of Washington
eScience Institute"

**Comment by sophieclayton** [comment]
after updating to the latest version of myria-python, i tried again and got this error:

```
D-128-208-239-205:aux_data sclayton$ myria_upload --user armbrustlab --program seaflow --relation gebco_bathy gebco_bathymetry.csv 
INFO:root:RelationKey = armbrustlab:seaflow:gebco_bathy
INFO:root:Schema = [('LONG_TYPE', ''), ('DOUBLE_TYPE', 'lon'), ('DOUBLE_TYPE', 'lat'), ('DOUBLE_TYPE', 'z')]
INFO:root:Myria schema: {"columnNames": ["", "lon", "lat", "z"], "columnTypes": ["LONG_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE"]}
INFO:root:Creating a binary file with struct.fmt=<qddd
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): rest.myria.cs.washington.edu
Traceback (most recent call last):
  File "/Users/sclayton/anaconda/bin/myria_upload", line 9, in <module>
    load_entry_point('myria-python==1.2.2', 'console_scripts', 'myria_upload')()
  File "/Users/sclayton/anaconda/lib/python2.7/site-packages/myria/cmd/upload_file.py", line 250, in main
    args.overwrite, **kwargs)
  File "/Users/sclayton/anaconda/lib/python2.7/site-packages/myria/connection.py", line 447, in upload_file
    % (r.status_code, r.text))
myria.errors.MyriaError: Error 400:
```

**Comment by dhalperi** [comment]
UGH OMG.

So, the issue appears to be that the first column has an empty name. Here is how I tested this:

1. get the first few lines of the bathy file into `broke.csv`
2. `myria_upload --relation broke_csv broke.csv` -- crashed with the same useless error.
3. add a name for the first column `noname0`
4. Works:
    ```
INFO:root:RelationKey = public:adhoc:broke_csv
INFO:root:Schema = [('LONG_TYPE', 'noname0'), ('DOUBLE_TYPE', 'lon'), ('DOUBLE_TYPE', 'lat'), ('DOUBLE_TYPE', 'z')]
INFO:root:Myria schema: {"columnNames": ["noname0", "lon", "lat", "z"], "columnTypes": ["LONG_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE", "DOUBLE_TYPE"]}
INFO:root:Creating a binary file with struct.fmt=<qddd
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): rest.myria.cs.washington.edu
{
    "created": null,
    "numTuples": 9,
    "uri": "https://rest.myria.cs.washington.edu:1776/dataset/user-public/program-adhoc/relation-broke_csv",
    "queryId": 62967,
    "relationKey": {
        "userName": "public",
        "relationName": "broke_csv",
        "programName": "adhoc"
    },
    "schema": {
        "columnNames": [
            "noname0",
            "lon",
            "lat",
            "z"
        ],
        "columnTypes": [
            "LONG_TYPE",
            "DOUBLE_TYPE",
            "DOUBLE_TYPE",
            "DOUBLE_TYPE"
        ]
    }
}
    ```

**Comment by dhalperi** [comment]
I'm going to follow this up with some bug fixes when I get into work:

1. Myria needs to return a useful error.
2. Myria-python needs to fill in missing column names with something helpful
3. we need tests on both sides to make sure this will never die.

For now, I'm trying your exactly upload command on the full file with the first column called `noname0`, but it looks like it's going to take a while. I'll let you know how it goes.

(How long did your attempts to upload take)?

**Comment by sophieclayton** [comment]
i'm not sure how long it took, but probably several hours before I got any
kind of error message...

On Thu, Feb 19, 2015 at 8:14 AM, Daniel Halperin <notifications@github.com>
wrote:

> I'm going to follow this up with some bug fixes when I get into work:
>
>    1. Myria needs to return a useful error.
>    2. Myria-python needs to fill in missing column names with something
>    helpful
>    3. we need tests on both sides to make sure this will never die.
>
> For now, I'm trying your exactly upload command on the full file with the
> first column called noname0, but it looks like it's going to take a
> while. I'll let you know how it goes.
>
> (How long did your attempts to upload take)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwescience/myria-python/issues/39#issuecomment-75080546>
> .
>



-- 
Sophie Clayton, PhD
School of Oceanography
Box 357940
University of Washington
Seattle, WA 98195, USA

tel: +1 (206) 685-1047
http://sophieclayton.github.io
http://armbrustlab.ocean.washington.edu/people/clayton

**Comment by dhalperi** [comment]
Uploaded now! Took quite a while for the uploader to run, but only 12.5m to actually upload the data. Wow, that uploaded needs some work.

I verified that the uploaded size is correct: 233312401 rows.

Go to town! And again, I'll be creating issues and bugfixes for all of these on the right repos.
