### ISSUE TITLE
Myria IPython module

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria-python#41]
We want something like this for Myria:

![screen shot 2015-03-13 at 3 06 14 pm](https://cloud.githubusercontent.com/assets/526415/6648052/8493a4ec-c992-11e4-80b0-2eefca04f76d.png)

See also https://dato.com/learn/gallery/?tagsApplied=&mediaKindsApplied=notebooks
and the Databricks keynote at Spark https://youtu.be/lO7LhVZrNwA?t=26m4s

**Comment by dhalperi** [comment]
@BrandonHaynes had started a discussion around a more noun-oriented Python client and I think I agree. Once we have the objects that correspond to the nouns, I think it will be easy to make them render and integrate nicely with IPython.

**Comment by dhalperi** [comment]
Looking into it, the key thing one needs to do is to implement a `_repr_html_` method:

![screen shot 2015-03-14 at 7 56 42 am](https://cloud.githubusercontent.com/assets/526415/6652100/b55fc9a6-ca1f-11e4-87a9-8a851f7de57d.png)

**Comment by dhalperi** [comment]
See also: http://nbviewer.ipython.org/github/profjsb/python-bootcamp/blob/fall2013/Lectures/13_AdvancedIPython/Custom%20Display%20Logic.ipynb#Implementing-special-display-methods

**Comment by BrandonHaynes** [comment]
Implemented in https://github.com/uwescience/myria-python/pull/48
