### ISSUE TITLE
MyriaRelation bug?

### ISSUE THREAD

**Issue by jortiz16** [uwescience/myria-python#50]
In a previous version of the docs, there was an example that would get relation info from the catalog and would instantiate a MyriaRelation. The following example does not work, but I don't remember if it has worked before (I remember trying out all the examples from the docs):

```
from myria import MyriaConnection, MyriaRelation
# Lower-level interaction via the API connection
connection = MyriaConnection(hostname='demo.myria.cs.washington.edu', port=8753)
datasets = connection.datasets()

# Higher-level interaction via relation and query instances
relation = MyriaRelation(datasets[0], connection=connection)
json = relation.to_dict()
print json
```

When running this, I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    relation = MyriaRelation(datasets[0], connection=connection)
  File "/Users/jortiz16/Documents/myria-python/myria/relation.py", line 29, in __init__
    else relation.name
AttributeError: 'dict' object has no attribute 'name'
```

If I did input the name of the relation (as the constructor says to do) from the example, i.e. using datasets[0]['relationKey'], I still get an error since it's looking for "relation.name" in relation.py. I'm not sure what this is referring to, perhaps I'm not using the constructor correctly

**Comment by BrandonHaynes** [comment]
There was indeed a change in the constructor behavior here with the `uri-magic`* branch -- is this occurring there or under master?  

I think that the correct invocation should look something like this**:

```Python
connection = MyriaConnection(hostname='demo.myria.cs.washington.edu', port=8753)
datasets = connection.datasets()
relation = MyriaRelation(datasets[0]['relationKey'], connection=connection)
```

Note the addition of the `relationKey` key.  Best guess is that the original form never worked -- oops.

* I misnamed the `uri-magic` branch -- it's the one with all of the IPython stuff and has nothing to do with URIs.  Oops.
** This requires a fix from the `uri-magic` branch, which should be merged in by Monday.

**Comment by BrandonHaynes** [comment]
No, this is totally a bug.  Will get the change merged in ASAP.

**Comment by jortiz16** [comment]
Thanks @BrandonHaynes ! When I tested this, I thought I was on master branch, but I will have to double check
